// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bookings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (id, created_at, updated_at, user_id, venue_id, start_time, end_time, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, venue_id, start_time, end_time, status, created_at, updated_at
`

type CreateBookingParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	VenueID   uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.VenueID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, id)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, user_id, venue_id, start_time, end_time, status, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookings = `-- name: GetBookings :many
SELECT id, user_id, venue_id, start_time, end_time, status, created_at, updated_at FROM bookings
`

func (q *Queries) GetBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VenueID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET updated_at = $2,
user_id = $3,
venue_id = $4,
start_time = $5,
end_time = $6,
status = $7
WHERE id = $1
RETURNING id, user_id, venue_id, start_time, end_time, status, created_at, updated_at
`

type UpdateBookingParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	UserID    uuid.UUID
	VenueID   uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.ID,
		arg.UpdatedAt,
		arg.UserID,
		arg.VenueID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VenueID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
