// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Booking struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	VenueID   uuid.UUID
	StartTime time.Time
	EndTime   time.Time
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Name      string
	Password  string
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Venue struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Location  string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
