// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: venues.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVenue = `-- name: CreateVenue :one
INSERT INTO venues (id, created_at, updated_at, name, location, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, location, type, created_at, updated_at
`

type CreateVenueParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Location  string
	Type      string
}

func (q *Queries) CreateVenue(ctx context.Context, arg CreateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, createVenue,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Location,
		arg.Type,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVenue = `-- name: DeleteVenue :exec
DELETE FROM venues WHERE id = $1
`

func (q *Queries) DeleteVenue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVenue, id)
	return err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, name, location, type, created_at, updated_at FROM venues WHERE id = $1
`

func (q *Queries) GetVenueByID(ctx context.Context, id uuid.UUID) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVenues = `-- name: GetVenues :many
SELECT id, name, location, type, created_at, updated_at FROM venues
`

func (q *Queries) GetVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, getVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVenue = `-- name: UpdateVenue :one
UPDATE venues
SET updated_at = $2,
name = $3,
location = $4,
type = $5
WHERE id = $1
RETURNING id, name, location, type, created_at, updated_at
`

type UpdateVenueParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Name      string
	Location  string
	Type      string
}

func (q *Queries) UpdateVenue(ctx context.Context, arg UpdateVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, updateVenue,
		arg.ID,
		arg.UpdatedAt,
		arg.Name,
		arg.Location,
		arg.Type,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
