version: "3.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "/app/quick-booking-api run"
    ports:
      - "5050:5050"
    environment:
      - API_PORT=5050
      - API_READ_TIMEOUT=10
      - API_WRITE_TIMEOUT=10
      - API_IDLE_TIMEOUT=20
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=qwerty
      - DB_NAME=booking
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
